### ISSUE TITLE
FA Asset Pack - Door Frame Issue

### ISSUE THREAD

**Issue by rpclarke** [Imagix/uvtt2fgu#12]
Hey there, thank you for this export.  I am just getting into DD and working on a project and came across something that you may or may not have the ability to do anything about.  But maybe we can get something changed.

In the Forgotten Adventures asset pack, there is door frames that can be placed separately from doors.  They are in the portal tool, so you end up with in effect, two doors.  I endedup remaking my map to not use them but would love to see support for door frames.

Anything I can do to help let me know. 

Thanks

**Comment by Imagix** [comment]
So you're talking essentially about an open door?  Or something else?
The best way to look at this would be for you do make a small map (like my sampleMap), which is basically just a square building with door(s) in the walls.  You want as few different things in the map to show just what you're trying to accomplish without having a whole bunch of other data that we'd have to wade through.   Attach the exported dd2vtt file here.  I would suggest exporting with the lowest pixel count that you can get away with; keeps the file size small.

**Comment by rpclarke** [comment]
[Test.zip](https://github.com/Imagix/uvtt2fgu/files/6683288/Test.zip)
Ok, here is the file, exported at 25 PPI. 

The single corridor is a normal door from the FA pack without using the door frame.  The two double wide corridors use the door frame and door which over laps.

**Comment by Imagix** [comment]
As far as the file can tell, there's 5 portals in there.  Seems that there's overlapping doors.  So, as far as the export is concerned, you've got 2 doors at the same place.  The question now is what are we expecting that to do?  What do you mean by "support door frames"?

**Comment by rpclarke** [comment]
Is there anything in the export that calls out that asset by its name maybe? door frames are not doors, so dont need to be opened or closed, and should just block LOS like a wall.   But with it being a portal asset, maybe there is nothing you can do with it, and I should make the suggestion to DD or FA..

**Comment by rpclarke** [comment]
But if its a rectangle, then.. I guess that means you cant do anything with it, unless you subtracted the door from the frame object

**Comment by Imagix** [comment]
No, the only differences between the door and the frame is that the frame is a little wider, and is marked as freestanding.   The assets (not surprisingly) are "gone" in the exported file as all the exported file really is, is a static map plus some line-of-sight and lighting details.  So the exported file doesn't even know if it is a "door frame" vs. a "door".  It's just a "portal".

A door frame _should_ block LOS?  I would have sorta expected it to not block LOS (I can look through a door frame), but rely on the door to block LOS.   I was somewhat thinking that in your map, perhaps the frame should have been marked to "allow light".  Which (unfortunately?) turns the frame into a window.  Which would allow light to pass, but would block movement.

**Comment by Imagix** [comment]
I'm sorta feeling like FA.  It would seem that they should be able to have an asset which can break a wall (perhaps some sort of "arch" asset?) which would make a gap in the wall.  And then the door assets that would fit in that gap.

Now, if DD also had a more distinct difference between Doors and Windows (even better, Secret Doors and Illusory Walls too :) ), that would be nice.

**Comment by rpclarke** [comment]
Actually its me thats the problem, thats totally it Imagix.  Use the door frame as the portal, then I am supposed to use the door object to place in the door frame gap.  Only 1 portal.  Just me being a noob. Thanks for helping me....  Sorry for the false positive. Thought I was on to something but nope. lol.  Not supposed to use a door frame portal and a door portal.  Just the frame portal and a door object. Nuances in the learning curve.

**Comment by Imagix** [comment]
No problem.  Maybe we were onto a new feature.  It's good.
