### ISSUE TITLE
Broken LoS when using uvtt2fgu on larger file

### ISSUE THREAD

**Issue by Mankomancer** [Imagix/uvtt2fgu#13]
LoS feature itself works fine, but players can move through walls (with spamming key presses or dragging their token).
Will assume problem is tied with file size.

Added the file in drive:
https://drive.google.com/file/d/1O4fVdVbCiOWn12kd1o_WNeLmTiky0umE/view?usp=sharing

Reference to forum:
https://www.fantasygrounds.com/forums/showthread.php?69484-Player-token-moving-through-walls

**Comment by Imagix** [comment]
Are players actually going through walls, or around the edges of doors?   Looking at the resultant file, and the comment from Smiteworks that the XML should only have 1 decimal point of precision, seems like most of the parts that have the decimal stuff is around doors.

**Comment by Mankomancer** [comment]
Try adding it in you FG and drag around the token. Here is an example, sometimes i can move through, sometimes i can just see through.
![image](https://user-images.githubusercontent.com/15931579/124396464-621ab780-dd12-11eb-9536-04be8353c882.png)

**Comment by Imagix** [comment]
Thanks.  There's a change in the "issue13" branch to round all of the numbers to 1 decimal point (as suggested in the forums).  I haven't had a chance to try it myself, if you're feeling somewhat adventurous, you could try it right now.

**Comment by Mankomancer** [comment]
> 
> 
> Thanks. There's a change in the "issue13" branch to round all of the numbers to 1 decimal point (as suggested in the forums). I haven't had a chance to try it myself, if you're feeling somewhat adventurous, you could try it right now.

Just tried, sadly still not resolved.
![image](https://user-images.githubusercontent.com/15931579/124396997-c8550980-dd15-11eb-93e9-dbb256f58e52.png)
![image](https://user-images.githubusercontent.com/15931579/124397013-d3a83500-dd15-11eb-8064-a10596b2266c.png)
![image](https://user-images.githubusercontent.com/15931579/124397019-dc007000-dd15-11eb-845a-c4418946d8aa.png)

**Comment by Mankomancer** [comment]
[uvtt2fgu-Imagix-issue13.zip](https://github.com/Imagix/uvtt2fgu/files/6760479/uvtt2fgu-Imagix-issue13.zip)
Added image and xml file. Below image just in case, that i used right version 👍 
![image](https://user-images.githubusercontent.com/15931579/124397068-40bbca80-dd16-11eb-9a77-e224d34fbdcf.png)

**Comment by Imagix** [comment]
Hmm... going to have to consult back with the Smiteworks folk.  Since those walls are drawn just as a sequence of points, and the new file is rounding to 1 decimal point, there should be no reason for a token to be able to escape through a corner.  I even made a version where there were no decimal points and the token could still escape.

**Comment by Mankomancer** [comment]
Cannot test now, but i could escape only when reached the corner. But it doesnt change the fact, that by "hugging" the wall, token was able to see through wall.
I find this situation, kind of fascinating. Because didnt expect that LoS will work at all, if something is not 100% right 🤔

**Comment by Imagix** [comment]
Yep, I'm seeing the same thing.  I'm wandering an Air Elemental around, and if I hug a wall, the LoS isn't even just that it can see both sides of the wall, the shape that it can see is weirdly shaped.

**Comment by Mankomancer** [comment]
Managed to find out what is the case ?

**Comment by Imagix** [comment]
Haven't forgotten about this.  Looking like it's an issue with FGU.  Information has been handed over to Smiteworks, waiting for a response from them.

**Comment by Imagix** [comment]
Smiteworks has confirmed the "token escaping the corner" issue and the fix should be in a forthcoming release.

**Comment by Mankomancer** [comment]
Glad to hear :)

**Comment by Imagix** [comment]
FGU beta 4.1.5 just got published with this fix:
Tokens could sometimes be moved through overlapping line-of-sight blockers. Fixed.

**Comment by Mankomancer** [comment]
Glad to hear 👍

**Comment by Imagix** [comment]
To be fair, I haven't actually tried the beta myself as it appears to be not backward compatible and didn't want to risk my campaigns :)  Did you actually try the beta, and did it fix the two issues we're looking at? (escaping the corner, and being able to see both sides of the wall?)

**Comment by Mankomancer** [comment]
Sorry, didnt notice the message. But havent had a chance to test it.
