### ISSUE TITLE
Suggestion: run on directory using config file

### ISSUE THREAD

**Issue by alexstreit** [Imagix/uvtt2fgu#6]
Keep it command-line only and operating system agnostic
Allow a configuration file to be specified ( -c <file>,  or look for a default "uvtt2fgu.yaml")
Config file specifies
 - source directory (default pwd)
 - img output directory (default pwd)
 - xml output directory (default pwd)

Runs over all .dd2vtt files and convert them
Default to check modified dates on output files to determine whether to overwrite them
Force (-f) overrides modified check
Add a remove (-r) option that removes the .dd2vtt file once processed

Reasoning:
Can put the executable or script file in a directory and run it with a click. Can export all .dd2vtt files into a single folder and then run the script to process changed ones.
With a cron job you could set up a "process queue" folder, using the -r parameter to keep the folder clean

**Comment by Imagix** [comment]
In principle, these are interesting suggestions, but a few thoughts come to mind (coming from a UNIX-y background):
1. Searching for a config file in the current working directory is generally not a good idea.  Means that if you run this in a directory that you don't control, the person who made that directory also controls your program.  Specifying it with a -c is good (since then you'd be asking for it).  Looking for that config file in some reasonable place (like ~/.config/uvtt2fgu.conf) is OK.  (I'd have to look up what the reasonable things to do on Windows and Mac OS are for this)
2. Running over all dd2vtt files by default seems "dangerous".  Turning it on in the aforementioned config file is good.
3. What's the value in doing the timestamp check? These conversions are pretty quick.  I suppose unless you're planning to run this on a directory of many maps.

**Comment by alexstreit** [comment]
1. Agree
2. While I expect the likelihood of there being a .dd2vtt file that you didn't want to convert in a directory that you run this in is quite small, I agree that it could be a configuration option. I think for quality of life it could make it very easy to work with. An alternative might be to have a -d "process directory" option.
3. timestamp its probably not necessary. To me it feels like --force should be the default behavior. I'm not sure in what scenario I wouldn't want to overwrite the output files, I'm sure there are valid use cases, I just couldn't think of them.

**Comment by Imagix** [comment]
For #2: if you can supply a -d, you can also supply *.dd2vtt.  The script will try to convert each file named in the command line.  I was thinking that the intent was to double-click on the script to convert everything in the directory, so you couldn't add a command-line parameter anyway.  (Thus the suggestion of turning it on in the config file)

#3: I guess I'm trying to be closer to the philosophy of do safe things by default, let the user override if desired.  We could also add this to the config file as well so it can default to overwrite.

**Comment by alexstreit** [comment]
Wasn't aware of the wildcard option, that makes sense. I didn't write clearly, I meant what you had written that there would be an option in the config file also. So totally agree.

On the philosophy, that makes sense. I had viewed this more something like a compiler, in that the output files are artifacts that are produced by the tool. Thinking about it more it is possible that someone would open an image file and edit it to add details, I hadn't really considered that before. An "overwrite by default" configuration option would still be helpful.

**Comment by Imagix** [comment]
If you take a look in the configfile branch, there's an updated script & readme with some of this implemented.  It's probably not looking in the right place on Windows for the default location of the configuration file (but the -c command-line should work).  Give that a try to see if it does what you'd like before I publish it.

**Comment by Imagix** [comment]
Ok, fixed up the Windows thing, and added the "alllocaldd2vttfiles" parameter for the configuration file (to convert all dd2vtt files if no files are specified on the command-line).

**Comment by alexstreit** [comment]
The path that gets returned by pathlib.home() is the user's home directory, but config files normally aren't stored there on windows. They're normally stored in the %localappdata% path. And on OSX it's another location still. I found this stackoverflow topic: https://stackoverflow.com/questions/11228645/where-to-store-the-configuration-files-of-python-applications-on-windows , which points to the appdirs library as a solution. Not sure if you want to add another dependency.

**Comment by Imagix** [comment]
A little digging around, and it seems that %APPDATA% is preferred for Windows, $HOME/Library/Preferences for Mac OS, and $XDG_CONFIG_HOME, or $HOME/.config for Linux.  Code updated.
