### ISSUE TITLE
something wrong with the latest version of dungeondraft 1.0.1.3

### ISSUE THREAD

**Issue by chalard87** [Imagix/uvtt2fgu#8]
When i create a simple figure with some walls and maps the image is not at the same place than the walls and lights. I haven't that problem with 1.0.1.1. Thanks.
![FantasyGrounds_Mg5wFa1vx0](https://user-images.githubusercontent.com/45460274/121801811-9df1be00-cc39-11eb-9dae-a77d8228c75b.png)
![FantasyGrounds_MPVI3BX4p5](https://user-images.githubusercontent.com/45460274/121801814-a0541800-cc39-11eb-8474-96cb2a725b35.png)

**Comment by Imagix** [comment]
Any chance of attaching your dd2vtt file (or sending it to me in some other manner)?

**Comment by Imagix** [comment]
The dd2vtt file will still be useful, but perhaps did you crop your map before exporting?

**Comment by chalard87** [comment]
Sorry for the delay I was at work. No cropping, roll20 format, no light, no grid. It does this every time (with other grid presets, with or without grid and lights). There is no problem with the old version 1.0.1.1
https://drive.google.com/drive/folders/16ni_tr9lj9_HRbO2_31FH4PVs0Kr2iWM?usp=sharing

**Comment by chalard87** [comment]
With some more tests it seems that the problem is linked to my fgu campaign. With a test campaign there is no problem (windows are treated like doors though, but it is probably because of a lack of understanding on my side). thank you.

**Comment by Imagix** [comment]
No problem.  I will be looking into cropped maps though... I suspect they might have the same symptoms as what you're seeing.

**Comment by Imagix** [comment]
In the exported file, it looks like they're all doors.  Note that for the tool's purposes, essentially all doors are closed.  In Dungeondraft, when you have the portal selected, you can choose whether it allows light, or does not.  If the portal is blocking light, it is a closed door.  If the portal allows light, it will be a window.

**Comment by chalard87** [comment]
I understand. Thanks a lot!Envoyé de mon Galaxy S21 Ultra 5G Orange
-------- Message d'origine --------De : Andre Kostur ***@***.***> Date : 14/06/2021  22:12  (GMT+01:00) À : Imagix/uvtt2fgu ***@***.***> Cc : chalard87 ***@***.***>, Author ***@***.***> Objet : Re: [Imagix/uvtt2fgu] something wrong with the latest version of dungeondraft 1.0.1.3 (#8) 
In the exported file, it looks like they're all doors.  Note that for the tool's purposes, essentially all doors are closed.  In Dungeondraft, when you have the portal selected, you can choose whether it allows light, or does not.  If the portal is blocking light, it is a closed door.  If the portal allows light, it will be a window.
